### ISSUE TITLE
Deprecation that will Stop Working in HA 2025.1

### ISSUE THREAD

**Issue by kaijk** [bushvin/hass-integrations#76] opened 2024-11-06 18:36 UTC
I get this message about Mopidy on startup:
```
2024-11-06 10:17:38.471 INFO (MainThread) [homeassistant.components.media_player] Setting up mopidy.media_player
2024-11-06 10:17:38.471 INFO (MainThread) [custom_components.mopidy.speaker.api] Creating Mopidy Websocket connection...
2024-11-06 10:17:38.477 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration mopidy with title: Mopidy Dining Room and entry_id: 01JC10EYMGFK0TE16HYMZTMA1Q, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

I presume this stack trace is related?  It was the next entry in the log
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2223, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1192, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 155, in report
    _LOGGER.warning(msg, stack_info=True)
```

**Comment by ondras12345** [comment] 2024-11-07 17:32
Duplicate of https://github.com/bushvin/hass-integrations/issues/70

**Closed** 2024-11-09 18:30 UTC
